{% set name = "elasticsearch" %}
{% set version = "7.16.3" %}
{% set bundle = "tar.gz" %}
{% set hash_val = "8adf8bc351ed55df7296be1009d38a1c999c0abc7d8700fa88533f1ad6087c5e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash_val }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - urllib3 >=1.21.1, <2
    - requests >=2.4.0,<3.0.0
    - certifi
    - aiohttp >=3,<4

test:
  imports:
    - elasticsearch
    - elasticsearch.client
    - elasticsearch.connection
    - elasticsearch.helpers

about:
  home: https://github.com/elastic/elasticsearch-py
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Python client for Elasticsearch
  doc_url: https://elasticsearch-py.readthedocs.io
  dev_url: https://github.com/elastic/elasticsearch-py

extra:
  recipe-maintainers:
    - ahlaw
    - sethmlarson
