{% set name = "elasticsearch" %}
{% set version = "9.5.1" %}
{% set bundle = "tar.gz" %}
{% set hash_val = "98210cd96c256dd9936f58e1c762aba94da7db7d38d058bb0fbaf7e4b9567146" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash_val }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
    - elastic-transport >=9.4.1,<10
    - python-dateutil
    - typing-extensions
    - sniffio
    - anyio

  run:
    - python >={{ python_min }}
    - elastic-transport >=9.2.0,<10
    - python-dateutil
    - typing-extensions
    - sniffio
    - anyio

test:
  requires:
    - python {{ python_min }}
  imports:
    - elasticsearch
    - elasticsearch.helpers

about:
  home: https://github.com/elastic/elasticsearch-py
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Python client for Elasticsearch
  doc_url: https://elasticsearch-py.readthedocs.io
  dev_url: https://github.com/elastic/elasticsearch-py

extra:
  recipe-maintainers:
    - joshmock
    - pquentin
    - margaretjgu
