{% set name = "elasticsearch" %}
{% set version = "8.5.3" %}
{% set bundle = "tar.gz" %}
{% set hash_val = "4b71ad05b36243c3b13f1c89b3ede4357011eece68917e293c43d4177d565838" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash_val }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
    - elastic-transport >=8,<9

  run:
    - python >=3.6
    - elastic-transport >=8,<9

test:
  imports:
    - elasticsearch
    - elasticsearch.helpers

about:
  home: https://github.com/elastic/elasticsearch-py
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: Python client for Elasticsearch
  doc_url: https://elasticsearch-py.readthedocs.io
  dev_url: https://github.com/elastic/elasticsearch-py

extra:
  recipe-maintainers:
    - ahlaw
    - sethmlarson
    - miriam-eid
